// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bondnkagwkoykufjmssu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvbmRua2Fnd2tveWt1Zmptc3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDAwOTQsImV4cCI6MjA2NTQ3NjA5NH0.gvHWucCN6h1_o-7SjNJfY1vMTSMslk_INg81nVgaQ7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);